[versions]
agp = "8.3.2"
kotlin = "2.0.21"
coreKtx = "1.12.0"
appcompat = "1.7.1"
constraintlayout = "2.1.4"
recyclerview = "1.3.2"
activityKtx = "1.9.0"
lifecycleRuntimeKtx = "2.8.6"
material = "1.12.0"
colorpickerview = "2.2.4"
amazonIonJava = "1.11.10"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
googleid = "1.1.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
colorpickerview = { group = "com.github.skydoves", name = "colorpickerview", version.ref = "colorpickerview" }
amazon-ion-java = { group = "com.amazon.ion", name = "ion-java", version.ref = "amazonIonJava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
